"""Add rejected column to adoption requests

Revision ID: bf43fffe094e
Revises: 
Create Date: 2025-05-08 20:50:29.607258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf43fffe094e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adoption_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejected', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adoption_request', schema=None) as batch_op:
        batch_op.drop_column('rejected')

    # ### end Alembic commands ###
